#pragma once

#define MYMATH_INCLUDE_SETTINGS

// Header includes if state equals 1
#define MYMATH_QUATERNION_STATE 1
#define MYMATH_MATRIX_STATE 1
#define MYMATH_VECTOR_STATE 1
#define MYMATH_DYNAMIC_MATRIX_STATE 1
#define MYMATH_DYNAMIC_VECTOR_STATE 1


#define MYMATH_MATRIX_S_MUL 1 
#define MYMATH_DIFFERENCE_SCHEME_STATE 1

